-- NeuLitTrace v2 — Card 1. Run after 01_setup.sql.
USE ROLE NEULIT_APP;
USE WAREHOUSE NEULIT_WH;
USE DATABASE NEULIT;
USE SCHEMA CORE;

CREATE OR REPLACE TABLE NEULIT.CORE.PAPERS (
  PMID        STRING       NOT NULL PRIMARY KEY,
  TITLE       STRING       NOT NULL,
  ABSTRACT    STRING       NOT NULL,
  JOURNAL     STRING,
  PUB_YEAR    NUMBER(4,0),
  CONDITION   STRING       NOT NULL,
  IS_RARE     BOOLEAN      NOT NULL,
  URL         STRING,
  SEARCH_BLOB STRING       NOT NULL,   -- TITLE || ' ' || ABSTRACT, what Cortex Search indexes
  LOADED_AT   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE NEULIT.CORE.CONDITIONS (
  CONDITION     STRING NOT NULL PRIMARY KEY,
  IS_RARE       BOOLEAN NOT NULL,
  PAPER_COUNT   NUMBER,
  DESCRIPTION   STRING,
  BRAIN_REGIONS ARRAY,
  CONDITION_VEC VECTOR(FLOAT, 768)     -- Cortex EMBED_TEXT_768 over DESCRIPTION
);

CREATE OR REPLACE TABLE NEULIT.CORE.TOKEN_LEDGER (
  EVENT_ID          STRING DEFAULT UUID_STRING(),
  REQUEST_ID        STRING NOT NULL,
  SESSION_ID        STRING,
  USER_ID           STRING,
  CALL_SITE         STRING NOT NULL,   -- hyde|relevance_check|refine|summary|citation_check|memory_distill
  MODEL             STRING NOT NULL,
  PROMPT_TOKENS     NUMBER NOT NULL,
  COMPLETION_TOKENS NUMBER NOT NULL,
  TOTAL_TOKENS      NUMBER NOT NULL,
  COST_USD          NUMBER(18,8) NOT NULL,
  LATENCY_MS        NUMBER,
  DEGRADED          BOOLEAN DEFAULT FALSE,
  OCCURRED_AT       TIMESTAMP_NTZ NOT NULL
);

CREATE OR REPLACE TABLE NEULIT.CORE.MODEL_PRICING (
  MODEL              STRING NOT NULL PRIMARY KEY,
  CREDITS_PER_MTOK_IN  NUMBER(18,8) NOT NULL,
  CREDITS_PER_MTOK_OUT NUMBER(18,8) NOT NULL,
  USD_PER_CREDIT       NUMBER(18,8) NOT NULL,
  EFFECTIVE_FROM     TIMESTAMP_NTZ NOT NULL
);

-- Seed MODEL_PRICING for the default model. NOTE: these credit rates are
-- placeholders copied from the Snowflake Cortex published rate card at
-- authoring time and MUST be reconciled against the account's actual
-- consumption table (SNOWFLAKE.ACCOUNT_USAGE / the Cortex pricing page) by
-- whoever runs this against a real account. See Handoff-Log.md.
MERGE INTO NEULIT.CORE.MODEL_PRICING AS tgt
USING (SELECT 'claude-3-5-sonnet' AS MODEL, 3.0 AS CREDITS_PER_MTOK_IN,
              15.0 AS CREDITS_PER_MTOK_OUT, 2.0 AS USD_PER_CREDIT,
              CURRENT_TIMESTAMP() AS EFFECTIVE_FROM) AS src
ON tgt.MODEL = src.MODEL
WHEN NOT MATCHED THEN INSERT (MODEL, CREDITS_PER_MTOK_IN, CREDITS_PER_MTOK_OUT, USD_PER_CREDIT, EFFECTIVE_FROM)
VALUES (src.MODEL, src.CREDITS_PER_MTOK_IN, src.CREDITS_PER_MTOK_OUT, src.USD_PER_CREDIT, src.EFFECTIVE_FROM);
