/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query */
        post: operations["query_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Query Stream
         * @description Runs the same pipeline as POST /query but over SSE, emitting `stage`
         *     events as the search loop progresses (hyde_expand, retrieval,
         *     relevance_check, refine_query, summarize, citation_check - the same
         *     stage names v1 used) followed by one `done` event with the full result.
         *     The frozen HTTP contract in plan-v2/00-SHARED-CONTRACTS.md section 4
         *     doesn't define this route's event shape, so it's ours to choose; matching
         *     v1's stage names is what frontend/src/components/progress-timeline.tsx
         *     already expects.
         */
        post: operations["query_stream_query_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo-contrast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Demo Contrast */
        get: operations["demo_contrast_demo_contrast_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conditions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Conditions */
        get: operations["conditions_conditions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/atlas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Default Atlas */
        get: operations["get_default_atlas_atlas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/atlas/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Query Atlas */
        get: operations["get_query_atlas_atlas_query_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/atlas/{condition_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Atlas */
        get: operations["get_atlas_atlas__condition_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/economics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Economics Summary */
        get: operations["economics_summary_economics_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/economics/request/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Economics Request */
        get: operations["economics_request_economics_request__request_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/economics/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Economics Ask */
        post: operations["economics_ask_economics_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memory/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Memory Profile */
        get: operations["memory_profile_memory_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memory/specialty": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Memory Specialty */
        post: operations["memory_specialty_memory_specialty_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memory/forget": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Memory Forget */
        post: operations["memory_forget_memory_forget_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memory/thread": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Memory Thread */
        get: operations["memory_thread_memory_thread_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BrainRegionOut */
        BrainRegionOut: {
            /** Name */
            name: string;
            /** Atlas Label */
            atlas_label: string;
            /** Region Literature */
            region_literature: string;
        };
        /** CallSiteBreakdown */
        CallSiteBreakdown: {
            /** Call Site */
            call_site: string;
            /** Requests */
            requests: number;
            /** Tokens */
            tokens: number;
            /** Cost Usd */
            cost_usd: number;
        };
        /** CallSiteCostOut */
        CallSiteCostOut: {
            /** Tokens */
            tokens: number;
            /** Cost Usd */
            cost_usd: number;
        };
        /** CitationOut */
        CitationOut: {
            /** Index */
            index: number;
            /** Pmid */
            pmid: string;
            /** Supported */
            supported: boolean | null;
            /** Note */
            note: string | null;
        };
        /**
         * ConditionOut
         * @description Consumed by backend/api/routes/conditions.py (Card 1). Keep in sync
         *     with backend.app.corpus.conditions.Condition if that shape ever changes.
         */
        ConditionOut: {
            /** Name */
            name: string;
            /** Rarity */
            rarity: string;
            /** Region Literature */
            region_literature: string;
            /** Atlas Label */
            atlas_label: string;
            /** Overlaps With */
            overlaps_with: string[];
        };
        /** ContrastPaperOut */
        ContrastPaperOut: {
            /** Pmid */
            pmid: string;
            /** Title */
            title: string;
            /** Condition */
            condition: string;
            /** Rarity */
            rarity: string;
        };
        /** CostOut */
        CostOut: {
            /** Total Tokens */
            total_tokens: number;
            /** Cost Usd */
            cost_usd: number;
            /** By Call Site */
            by_call_site: {
                [key: string]: components["schemas"]["CallSiteCostOut"];
            };
        };
        /** DemoContrastResponse */
        DemoContrastResponse: {
            /** Query */
            query: string;
            /** Naive */
            naive: components["schemas"]["ContrastPaperOut"][];
            /** Weighted */
            weighted: components["schemas"]["ContrastPaperOut"][];
            /** Rare Case Pmid */
            rare_case_pmid: string;
        };
        /** EconomicsAskOut */
        EconomicsAskOut: {
            /** Answer */
            answer: string;
            /** Sql */
            sql: string;
            /** Rows */
            rows: {
                [key: string]: unknown;
            }[];
        };
        /** EconomicsAskRequest */
        EconomicsAskRequest: {
            /** Question */
            question: string;
        };
        /** EconomicsRequestOut */
        EconomicsRequestOut: {
            /** Request Id */
            request_id: string;
            /** Calls */
            calls: components["schemas"]["RequestCallOut"][];
            /** Total Cost Usd */
            total_cost_usd: number;
        };
        /** EconomicsSummaryOut */
        EconomicsSummaryOut: {
            /** Total Requests */
            total_requests: number;
            /** Total Tokens */
            total_tokens: number;
            /** Total Cost Usd */
            total_cost_usd: number;
            /** By Call Site */
            by_call_site: components["schemas"]["CallSiteBreakdown"][];
            /** By Hour */
            by_hour: components["schemas"]["HourlyBreakdown"][];
        };
        /** ForgetRequest */
        ForgetRequest: {
            /** User Id */
            user_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HourlyBreakdown */
        HourlyBreakdown: {
            /** Hour Iso */
            hour_iso: string;
            /** Tokens */
            tokens: number;
            /** Cost Usd */
            cost_usd: number;
        };
        /** MemoryOut */
        MemoryOut: {
            /** Applied */
            applied: boolean;
            /** Seen Filtered */
            seen_filtered: number;
            /** Profile Used */
            profile_used: boolean;
            /** Distilled Context */
            distilled_context: string;
        };
        /** PaperOut */
        PaperOut: {
            /** Pmid */
            pmid: string;
            /** Title */
            title: string;
            /** Abstract */
            abstract: string;
            /** Journal */
            journal: string;
            /** Year */
            year: number;
            /** Condition */
            condition: string;
            /** Israre */
            isRare: boolean;
            /** Url */
            url: string;
        };
        /** ProfileOut */
        ProfileOut: {
            /** User Id */
            user_id: string;
            /** Specialty */
            specialty: string | null;
            /** Conditions Explored */
            conditions_explored: string[];
            /** Query Count */
            query_count: number;
            /** Distilled Context */
            distilled_context: string;
            /** Seen Pmid Count */
            seen_pmid_count: number;
        };
        /** QueryRequest */
        QueryRequest: {
            /** Query */
            query: string;
            /** Session Id */
            session_id: string;
            /** User Id */
            user_id: string;
            /**
             * Personalize
             * @default false
             */
            personalize: boolean;
        };
        /** QueryResponse */
        QueryResponse: {
            /** Request Id */
            request_id: string;
            /** Summary Markdown */
            summary_markdown: string;
            /** Citations */
            citations: components["schemas"]["CitationOut"][];
            /** Papers */
            papers: components["schemas"]["ScoredPaperOut"][];
            /** Trace */
            trace: components["schemas"]["TraceRoundOut"][];
            region: components["schemas"]["BrainRegionOut"] | null;
            memory: components["schemas"]["MemoryOut"];
            cost: components["schemas"]["CostOut"];
        };
        /** RequestCallOut */
        RequestCallOut: {
            /** Call Site */
            call_site: string;
            /** Prompt Tokens */
            prompt_tokens: number;
            /** Completion Tokens */
            completion_tokens: number;
            /** Cost Usd */
            cost_usd: number;
            /** Latency Ms */
            latency_ms: number;
            /** Degraded */
            degraded: boolean;
        };
        /** ScoredPaperOut */
        ScoredPaperOut: {
            paper: components["schemas"]["PaperOut"];
            /** Score */
            score: number;
            /** Lexicalscore */
            lexicalScore: number;
            /** Semanticscore */
            semanticScore: number;
            /** Raritymultiplier */
            rarityMultiplier: number;
            /** Memorymultiplier */
            memoryMultiplier: number;
        };
        /** SpecialtyRequest */
        SpecialtyRequest: {
            /** User Id */
            user_id: string;
            /** Specialty */
            specialty: string;
        };
        /** ThreadOut */
        ThreadOut: {
            /** Session Id */
            session_id: string;
            /** User Id */
            user_id: string;
            /** Queries */
            queries: string[];
            /** Pmids Shown */
            pmids_shown: string[];
        };
        /** TraceRoundOut */
        TraceRoundOut: {
            /** Iteration */
            iteration: number;
            /** Retrieved Pmids */
            retrieved_pmids: string[];
            /** Relevant */
            relevant: boolean;
            /** Confidence */
            confidence: number;
            /** Note */
            note: string;
            /** Memory Applied */
            memory_applied: boolean;
            /** Seen Filtered */
            seen_filtered: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    query_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_stream_query_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    demo_contrast_demo_contrast_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoContrastResponse"];
                };
            };
        };
    };
    conditions_conditions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConditionOut"][];
                };
            };
        };
    };
    get_default_atlas_atlas_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_query_atlas_atlas_query_get: {
        parameters: {
            query?: {
                conditions?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_atlas_atlas__condition_name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condition_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    economics_summary_economics_summary_get: {
        parameters: {
            query?: {
                window?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EconomicsSummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    economics_request_economics_request__request_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EconomicsRequestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    economics_ask_economics_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EconomicsAskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EconomicsAskOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    memory_profile_memory_profile_get: {
        parameters: {
            query: {
                user_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    memory_specialty_memory_specialty_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpecialtyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    memory_forget_memory_forget_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    memory_thread_memory_thread_get: {
        parameters: {
            query: {
                user_id: string;
                session_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
